machine_id: kazi_ga
num_workers: 4
output_dir: output/kazi_ga
dataset_jsonl: "datasets/combined_dataset.jsonl"

assignments:
  - grid: [30, 30]
    patterns: [stripes]
    ga_config: long
    genome_len:
      stripes: 350

  - grid: [30, 100]
    patterns: [left_right]
    ga_config: default
    genome_len:
      left_right: 400

  - grid: [50, 50]
    patterns: [left_right, voronoi]
    ga_config: medium
    genome_len:
      left_right: 600
      voronoi: 800
